# Generated by Django 3.2.8 on 2021-10-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=45)),
                ('person_last_name', models.CharField(max_length=45)),
                ('person_address', models.CharField(max_length=45)),
                ('person_phone', models.CharField(max_length=45)),
                ('person_dni', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Person_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_type_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Price_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=13)),
                ('shop_price', models.DecimalField(decimal_places=2, max_digits=13)),
                ('star_date', models.DateTimeField()),
                ('user_update', models.CharField(max_length=100)),
                ('date_update', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product_provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_code', models.CharField(max_length=45)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('nit', models.CharField(max_length=45)),
                ('url', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tax_name', models.CharField(max_length=15)),
                ('creation_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('half_payment', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ticket_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('devolution_request', models.DateTimeField()),
                ('devolution_approved', models.DateTimeField()),
                ('description_devolution', models.CharField(max_length=45)),
            ],
        ),
    ]
