# Generated by Django 3.2.8 on 2021-10-28 00:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_price_product_date_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_product',
            name='date_update',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 27, 19, 56, 4, 978043)),
        ),
    ]
