# Generated by Django 3.2.8 on 2021-10-31 21:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_auto_20211028_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='price_product',
            name='fk_id_product_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.product_provider'),
        ),
        migrations.AlterField(
            model_name='price_product',
            name='date_update',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 31, 16, 53, 21, 233260)),
        ),
    ]
