# Generated by Django 3.2.8 on 2021-11-01 03:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_auto_20211031_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_product',
            name='date_update',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 31, 22, 17, 23, 935170)),
        ),
        migrations.AlterField(
            model_name='price_product',
            name='sale_price',
            field=models.DecimalField(decimal_places=4, max_digits=13),
        ),
        migrations.AlterField(
            model_name='price_product',
            name='shop_price',
            field=models.DecimalField(decimal_places=4, max_digits=13),
        ),
    ]
