# Generated by Django 3.2.8 on 2021-11-01 23:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_auto_20211031_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fk_id_product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.product_type'),
        ),
        migrations.AddField(
            model_name='product_provider',
            name='fk_id_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.product'),
        ),
        migrations.AddField(
            model_name='product_provider',
            name='fk_id_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.provider'),
        ),
        migrations.AddField(
            model_name='product_provider',
            name='stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fk_id_person_cachier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_id_person_cachier', to='productos.person'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fk_id_person_costumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_id_person_costumer', to='productos.person'),
        ),
        migrations.AddField(
            model_name='ticket_detail',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ticket_detail',
            name='fk_id_ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.ticket'),
        ),
        migrations.AlterField(
            model_name='price_product',
            name='date_update',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 18, 14, 43, 763844)),
        ),
        migrations.AlterField(
            model_name='price_product',
            name='user_update',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Tax_price_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_id_price_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.price_product')),
                ('fk_id_tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.tax')),
            ],
        ),
        migrations.CreateModel(
            name='Person_person_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_id_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.person')),
                ('fk_id_person_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.person_type')),
            ],
        ),
        migrations.AddField(
            model_name='ticket_detail',
            name='fk_id_tax_price_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.tax_price_product'),
        ),
    ]
