# Generated by Django 3.2.8 on 2021-11-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_alter_price_product_date_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_product',
            name='date_update',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='price_product',
            name='start_date',
            field=models.DateField(),
        ),
    ]
