# Generated by Django 3.2.8 on 2021-11-15 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_auto_20211114_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='creation_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_date',
            field=models.DateField(),
        ),
    ]
