# Generated by Django 3.2.8 on 2021-11-15 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0013_auto_20211114_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_detail',
            name='devolution_approved',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket_detail',
            name='devolution_request',
            field=models.DateField(null=True),
        ),
    ]
