# Generated by Django 3.2.8 on 2021-11-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0016_alter_product_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_provider',
            name='bar_code',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
