# Generated by Django 3.2.8 on 2021-11-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0017_alter_product_provider_bar_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='tax_name',
            field=models.CharField(max_length=20),
        ),
    ]
